import { PROJECTS } from '../constants';

const defaultSelectedProject = {
  id: 10791045,
  node_id: 'MDEwOlJlcG9zaXRvcnkxMDc5MTA0NQ==',
  name: 'ACEView',
  full_name: 'mralexgray/ACEView',
  private: false,
  owner: {
    login: 'mralexgray',
    id: 262517,
    node_id: 'MDQ6VXNlcjI2MjUxNw==',
    avatar_url: 'https://avatars3.githubusercontent.com/u/262517?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mralexgray',
    html_url: 'https://github.com/mralexgray',
    followers_url: 'https://api.github.com/users/mralexgray/followers',
    following_url: 'https://api.github.com/users/mralexgray/following{/other_user}',
    gists_url: 'https://api.github.com/users/mralexgray/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mralexgray/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mralexgray/subscriptions',
    organizations_url: 'https://api.github.com/users/mralexgray/orgs',
    repos_url: 'https://api.github.com/users/mralexgray/repos',
    events_url: 'https://api.github.com/users/mralexgray/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mralexgray/received_events',
    type: 'User',
    site_admin: false
  },
  html_url: 'https://github.com/mralexgray/ACEView',
  description: 'Use the wonderful ACE editor in your Cocoa applications',
  fork: true,
  url: 'https://api.github.com/repos/mralexgray/ACEView',
  forks_url: 'https://api.github.com/repos/mralexgray/ACEView/forks',
  keys_url: 'https://api.github.com/repos/mralexgray/ACEView/keys{/key_id}',
  collaborators_url: 'https://api.github.com/repos/mralexgray/ACEView/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/mralexgray/ACEView/teams',
  hooks_url: 'https://api.github.com/repos/mralexgray/ACEView/hooks',
  issue_events_url: 'https://api.github.com/repos/mralexgray/ACEView/issues/events{/number}',
  events_url: 'https://api.github.com/repos/mralexgray/ACEView/events',
  assignees_url: 'https://api.github.com/repos/mralexgray/ACEView/assignees{/user}',
  branches_url: 'https://api.github.com/repos/mralexgray/ACEView/branches{/branch}',
  tags_url: 'https://api.github.com/repos/mralexgray/ACEView/tags',
  blobs_url: 'https://api.github.com/repos/mralexgray/ACEView/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/mralexgray/ACEView/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/mralexgray/ACEView/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/mralexgray/ACEView/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/mralexgray/ACEView/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/mralexgray/ACEView/languages',
  stargazers_url: 'https://api.github.com/repos/mralexgray/ACEView/stargazers',
  contributors_url: 'https://api.github.com/repos/mralexgray/ACEView/contributors',
  subscribers_url: 'https://api.github.com/repos/mralexgray/ACEView/subscribers',
  subscription_url: 'https://api.github.com/repos/mralexgray/ACEView/subscription',
  commits_url: 'https://api.github.com/repos/mralexgray/ACEView/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/mralexgray/ACEView/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/mralexgray/ACEView/comments{/number}',
  issue_comment_url: 'https://api.github.com/repos/mralexgray/ACEView/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/mralexgray/ACEView/contents/{+path}',
  compare_url: 'https://api.github.com/repos/mralexgray/ACEView/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/mralexgray/ACEView/merges',
  archive_url: 'https://api.github.com/repos/mralexgray/ACEView/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/mralexgray/ACEView/downloads',
  issues_url: 'https://api.github.com/repos/mralexgray/ACEView/issues{/number}',
  pulls_url: 'https://api.github.com/repos/mralexgray/ACEView/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/mralexgray/ACEView/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/mralexgray/ACEView/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/mralexgray/ACEView/labels{/name}',
  releases_url: 'https://api.github.com/repos/mralexgray/ACEView/releases{/id}',
  deployments_url: 'https://api.github.com/repos/mralexgray/ACEView/deployments',
  created_at: '2013-06-19T12:15:04Z',
  updated_at: '2015-11-24T01:14:10Z',
  pushed_at: '2014-05-09T01:36:23Z',
  git_url: 'git://github.com/mralexgray/ACEView.git',
  ssh_url: 'git@github.com:mralexgray/ACEView.git',
  clone_url: 'https://github.com/mralexgray/ACEView.git',
  svn_url: 'https://github.com/mralexgray/ACEView',
  homepage: null,
  size: 1733,
  stargazers_count: 0,
  watchers_count: 0,
  language: 'Objective-C',
  has_issues: false,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: 1,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: {
    key: 'bsd-3-clause',
    name: 'BSD 3-Clause "New" or "Revised" License',
    spdx_id: 'BSD-3-Clause',
    url: 'https://api.github.com/licenses/bsd-3-clause',
    node_id: 'MDc6TGljZW5zZTU='
  },
  forks: 1,
  open_issues: 0,
  watchers: 0,
  default_branch: 'master'
};

const selectProjectReducer = (state = defaultSelectedProject, { type, project }) => {
  if (type === PROJECTS.VIEW) {
    return { ...project };
  }
  return state;
};

export default selectProjectReducer;
